const bodyParser = require('body-parser');
const port = process.env.PORT || 3000;
const cors = require('cors');
const express = require('express');
const app = express();
const path = require('path');
const {userRoutes} = require('./user');
app.use(express.static(path.join(__dirname,'..','public')));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:false}));
app.use(cors());
app.use('/users',userRoutes);
module.exports = {app,port,userRoutes};